CREATE TABLE meters (objectid text,
meter_number text,
status text,
pay_by_cell_number text,
meter_hours text,
parking_facility_name text,
facility text,
borough text,
on_street text,
side_of_street text,
from_street text,
to_street text,
lat float,
long float,
x float,
y float,
location text) 
